<Project>
    <PropertyGroup>
        <Authors>Hamunii</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Hamunii/MonoMod.RuntimeDetour.HookGen.MSBuild</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <VersionPrefix>0.1.1</VersionPrefix>
        <VersionSuffix>dev</VersionSuffix>
    </PropertyGroup>
</Project>