<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>

        <Description>Yet another assembly publicizer/stripper</Description>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <!-- <PackageReference Include="IsExternalInit" Version="1.0.3" PrivateAssets="all" Private="true"/> -->
        <PackageReference Include="MonoMod.RuntimeDetour.HookGen" Version="22.07.31.01" />
        <PackageReference Include="Mono.Cecil" Version="0.11.4.0"/>
        <!-- <PackageReference Include="BepInEx.Core" Version="5.*" /> -->
        <!-- <PackageReference Include="MonoMod" Version="22.*" /> -->
    </ItemGroup>
</Project>
